#!/bin/sh
while read file
do
	case "$1" in
		"C-d")
			mv "$file" "~/.trash";;
		"C-r")
			convert -rotate 90 "$file" "$file";;
		"C-c")
			# cat "$file" | xclip -selection clipboard;;
			cat "$file" | powershell.exe 'Get-Item ' `python ~/ri_script/wsl_2_abspath.py "$file"` '| Set-Clipboard';;
		"C-p")
			echo -n "$file" | xclip -selection clipboard;;
		"C-w")
			nitrogen --save --set-zoom-fill "$file";;
		esac

done
