confirmonquit: false
git:
  autofetch: true
  merging:
    manualcommit: false
  skiphookprefix: WIP
  paging:
    colorArg: always
    pager: delta --dark --paging=never --24-bit-color=never 
gui:
  commitlength:
    show: true
  mouseevents: false
  scrollheight: 2
  scrollpastbottom: true
  theme:
    lightTheme: false
    activeBorderColor:
      - cyan
      - bold
    inactiveBorderColor:
      - white
    optionsTextColor:
      - blue
    selectedLineBgColor:
      - default
    selectedRangeBgColor:
      - blue
reporting: "off"
splashupdatesindex: 0
startuppopupversion: 1
keybinding:
  universal:
    prevItem-alt: 'k'
    nextItem-alt: 'j'
    prevBlock-alt: 'h'
    nextBlock-alt: 'l'
    nextMatch: '='
    prevMatch: '-'
    new: 'n'
    edit: 'e'
    openFile: 'O'
    scrollUpMain-alt1: 'K'
    scrollDownMain-alt1: 'J'
    scrollUpMain-alt2: '<c-k>'
    scrollDownMain-alt2: '<c-j>'
    undo: 'u'
    redo: '<c-r>'
    diffingMenu: 'M'
    filteringMenu: '<c-f>'
  files:
    ignoreFile: 'I'
  commits:
    moveDownCommit: '<c-j>'
    moveUpCommit: '<c-k>'
  branches:
    viewGitFlowOptions: 'I'
    setUpstream: 'U'
